name: Publish on modrinth

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: ./gradlew build
            - uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: 6N50GaPF
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
